ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "expo/scripts/autolinking.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

def patch_fmt_consteval_bug(installer)
  fmt_base = File.join(
    installer.sandbox.root.to_s,
    'fmt',
    'include',
    'fmt',
    'base.h'
  )

  return unless File.exist?(fmt_base)

  content = File.read(fmt_base)
  original = <<~CODE
      using checker =
          detail::format_string_checker<Char, remove_cvref_t<Args>...>;
      detail::parse_format_string<true>(str_, checker(s));
  CODE
  replacement = <<~CODE
      using checker =
          detail::format_string_checker<Char, remove_cvref_t<Args>...>;
      if constexpr (detail::is_compile_string<S>::value) {
        FMT_CONSTEXPR auto sv = basic_string_view<Char>(S());
        detail::parse_format_string<true>(sv, checker(sv));
      } else {
        detail::parse_format_string<true>(str_, checker(s));
      }
  CODE

  return unless content.include?(original)

  File.write(fmt_base, content.sub(original, replacement))
  Pod::UI.puts 'Patched fmt/base.h for newer clang consteval checks'.yellow
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ScrollEdgeBarExample' do
  use_expo_modules!

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    patch_fmt_consteval_bug(installer)
  end
end
